{% set version = "0.0-32" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-tkrplot
  version: "{{ version|replace("-", "_") }}"

source:
  url:
    - {{ cran_mirror }}/src/contrib/tkrplot_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tkrplot/tkrplot_{{ version }}.tar.gz
  sha256: a37a591ed87b890d0f631227a39a7586682f6fcc72e154d499d804fd38d477ab

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win] 
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib('c') }}
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - xorg-xproto                  # [linux]
    - r-base
    - tk
  run:
    - r-base

test:
  commands:
    - $R -e "library('tkrplot')"           # [not win]
    - "\"%R%\" -e \"library('tkrplot')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=tkrplot
  license: GPL-2.0-or-later
  summary: Simple mechanism for placing R graphics in a Tk widget.
  license_family: GPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
