{% set version = "0.0-27" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-tkrplot
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tkrplot_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tkrplot/tkrplot_{{ version }}.tar.gz
  sha256: c99211919414400b0f579e1354407f2e154cfe85533d324bcf9c68172c2772a5

build:
  number: 3
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}          # [not win] 
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib('c') }}
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - tk
  run:
    - r-base

test:
  commands:
    - $R -e "library('tkrplot')"           # [not win]
    - "\"%R%\" -e \"library('tkrplot')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=tkrplot
  license: GPL-2.0-or-later
  summary: Simple mechanism for placing R graphics in a Tk widget.
  license_family: GPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
