# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "HaLmNFlr6JUWQsK41EabRnZkDFWrABnZg9dFSB5tI2lHqfAHHXJCjrjoOZ1c/aSt8h5esK8gTyJJdAnNS1axhBBb0veUtQ8i4GrzhRDS4ynZC+/ShYav0DIBPJ4Hlbl1HEdXbY4bN6u/AlTpNxKtV7YykzPUPLw85uUHw5BVXXJgBvr2E1p58s8GD+eG3ltWkJz0JEjcohpnfqSD+1I0H2rVN6aIAg2I9g1Zc5KJMBgqKx+EdA+RniFPFWCBX4fnHUeUxTL3BMuGhj2pjzTvVsjm1KJtJvAf21QCxENnoJzG/rgMQH8ISAM0pjttOSx1QXsn7SC6/UVE4PLZqPUTwXq6+TabuSpCeeZsKT1ZCIiPIu6JefGc1+uKJssQYchhOOMjk7eZk1YOBcFqYfrx/VZDdfbL889MMdu8/0UVLxwmKr6bKZIaeb2s1cbmbI0Z818uZxQeWMMV8BFw058bAYPb6LIiUbLpDy+lfdxqeUWe01h29JX8KslkvBw9U6kQF2bkjYLZUfx0iMvOgBFi9weEaTMD0N5pfuvcBwjlstfrFt/2uPBmTPH7FQip5ag1SnVNWLohBAkwk5v89pPt6tUuFuapcCsAEpDCwtgPzJU43JgbMnNPyV6h4/bPSSNMxaV/fW11/h4s7jLqNGYZ31ck1jpFQ91GfHKK9ijrhTE="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml