appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: HaLmNFlr6JUWQsK41EabRnZkDFWrABnZg9dFSB5tI2lHqfAHHXJCjrjoOZ1c/aSt8h5esK8gTyJJdAnNS1axhBBb0veUtQ8i4GrzhRDS4ynZC+/ShYav0DIBPJ4Hlbl1HEdXbY4bN6u/AlTpNxKtV7YykzPUPLw85uUHw5BVXXJgBvr2E1p58s8GD+eG3ltWkJz0JEjcohpnfqSD+1I0H2rVN6aIAg2I9g1Zc5KJMBgqKx+EdA+RniFPFWCBX4fnHUeUxTL3BMuGhj2pjzTvVsjm1KJtJvAf21QCxENnoJzG/rgMQH8ISAM0pjttOSx1QXsn7SC6/UVE4PLZqPUTwXq6+TabuSpCeeZsKT1ZCIiPIu6JefGc1+uKJssQYchhOOMjk7eZk1YOBcFqYfrx/VZDdfbL889MMdu8/0UVLxwmKr6bKZIaeb2s1cbmbI0Z818uZxQeWMMV8BFw058bAYPb6LIiUbLpDy+lfdxqeUWe01h29JX8KslkvBw9U6kQF2bkjYLZUfx0iMvOgBFi9weEaTMD0N5pfuvcBwjlstfrFt/2uPBmTPH7FQip5ag1SnVNWLohBAkwk5v89pPt6tUuFuapcCsAEpDCwtgPzJU43JgbMnNPyV6h4/bPSSNMxaV/fW11/h4s7jLqNGYZ31ck1jpFQ91GfHKK9ijrhTE=}
